require('dotenv').config();
const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
const User = require('./models/User');
const Mentor = require('./models/Mentor');
const connectDB = require('./config/db');

// Helper function to generate random values
const randomPrice = () => Math.floor(Math.random() * 30) + 35; // 35-65
const randomRating = () => (Math.random() * 0.4 + 4.5).toFixed(1); // 4.5-4.9
const randomSessions = () => Math.floor(Math.random() * 100) + 50; // 50-150
const randomRatingsCount = () => Math.floor(Math.random() * 30) + 15; // 15-45

const africanCities = [
  "Lagos, Nigeria", "Nairobi, Kenya", "Accra, Ghana", "Cape Town, South Africa",
  "Johannesburg, South Africa", "Cairo, Egypt", "Dakar, Senegal", "Addis Ababa, Ethiopia",
  "Kigali, Rwanda", "Dar es Salaam, Tanzania", "Kampala, Uganda", "Abuja, Nigeria",
  "Casablanca, Morocco", "Tunis, Tunisia", "Lusaka, Zambia", "Harare, Zimbabwe"
];

const availabilityOptions = [
  ["Monday", "Wednesday", "Friday"],
  ["Tuesday", "Thursday", "Saturday"],
  ["Monday", "Tuesday", "Thursday"],
  ["Wednesday", "Friday", "Sunday"],
  ["Monday", "Wednesday", "Saturday", "Sunday"],
  ["Tuesday", "Thursday", "Friday", "Saturday"]
];

const getRandomCity = () => africanCities[Math.floor(Math.random() * africanCities.length)];
const getRandomAvailability = () => availabilityOptions[Math.floor(Math.random() * availabilityOptions.length)];

const mentorsData = [
  // PAINTING (3 mentors)
  {
    name: "Amara Okonkwo",
    email: "amara.okonkwo@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Award-winning visual artist specializing in contemporary African art. I blend traditional techniques with modern digital tools to create powerful narratives.",
    profilePicture: "https://i.pravatar.cc/300?img=45",
    location: "Lagos, Nigeria",
    expertise: ["Painting", "Digital Art", "Mixed Media", "Art History", "Portfolio Development"],
    languages: ["English", "Yoruba", "Igbo"],
    pricePerSession: 45,
    experience: "12 years",
    education: "MFA in Fine Arts, University of Lagos",
    rating: 4.8,
    totalRatings: 24,
    completedSessions: 87,
    availability: ["Monday", "Wednesday", "Friday", "Saturday"]
  },
  {
    name: "Yusuf Kamara",
    email: "yusuf.kamara@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Landscape painter capturing the beauty of African sunsets and wildlife. I teach oil painting, watercolor techniques, and plein air painting.",
    profilePicture: "https://i.pravatar.cc/300?img=60",
    location: getRandomCity(),
    expertise: ["Painting", "Oil Painting", "Watercolor", "Landscape Art", "Color Theory"],
    languages: ["English", "French"],
    pricePerSession: randomPrice(),
    experience: "9 years",
    education: "BA Fine Arts",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },
  {
    name: "Nia Mensah",
    email: "nia.mensah@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Abstract expressionist using painting to explore identity and culture. I help artists find their unique visual language through experimentation.",
    profilePicture: "https://i.pravatar.cc/300?img=41",
    location: getRandomCity(),
    expertise: ["Painting", "Abstract Art", "Acrylic Painting", "Mixed Media", "Art Critique"],
    languages: ["English", "Twi"],
    pricePerSession: randomPrice(),
    experience: "7 years",
    education: "MFA Studio Art",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },

  // DIGITAL ART (3 mentors)
  {
    name: "Kofi Asare",
    email: "kofi.asare@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Digital illustrator creating vibrant Afrofuturistic artwork. I teach Procreate, digital painting techniques, and building an online art portfolio.",
    profilePicture: "https://i.pravatar.cc/300?img=14",
    location: getRandomCity(),
    expertise: ["Digital Art", "Procreate", "Digital Illustration", "Concept Art", "Character Design"],
    languages: ["English"],
    pricePerSession: randomPrice(),
    experience: "6 years",
    education: "Digital Arts Certificate",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },
  {
    name: "Zainab Okeke",
    email: "zainab.okeke@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Freelance digital artist specializing in editorial illustrations and book covers. I'll teach you how to use Photoshop and Illustrator professionally.",
    profilePicture: "https://i.pravatar.cc/300?img=38",
    location: getRandomCity(),
    expertise: ["Digital Art", "Adobe Photoshop", "Adobe Illustrator", "Editorial Illustration", "Freelancing"],
    languages: ["English", "Hausa"],
    pricePerSession: randomPrice(),
    experience: "8 years",
    education: "BA Graphic Arts",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },
  {
    name: "Themba Nkosi",
    email: "themba.nkosi@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Digital matte painter for film and games. I create breathtaking digital environments and teach advanced compositing techniques.",
    profilePicture: "https://i.pravatar.cc/300?img=53",
    location: getRandomCity(),
    expertise: ["Digital Art", "Matte Painting", "Digital Compositing", "Environment Design", "Photoshop"],
    languages: ["English", "Zulu"],
    pricePerSession: randomPrice(),
    experience: "10 years",
    education: "Digital Media Arts Degree",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },

  // GRAPHIC DESIGN (3 mentors)
  {
    name: "Kwame Mensah",
    email: "kwame.mensah@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Graphic designer with a passion for Afrofuturism and bold visual storytelling. I help creatives develop their unique style.",
    profilePicture: "https://i.pravatar.cc/300?img=12",
    location: "Accra, Ghana",
    expertise: ["Graphic Design", "Illustration", "Branding", "Adobe Creative Suite", "UI/UX Design"],
    languages: ["English", "Twi", "French"],
    pricePerSession: 40,
    experience: "8 years",
    education: "BA in Graphic Design, Kwame Nkrumah University",
    rating: 4.9,
    totalRatings: 31,
    completedSessions: 102,
    availability: ["Tuesday", "Thursday", "Saturday"]
  },
  {
    name: "Aisha Diallo",
    email: "aisha.diallo@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Brand identity designer helping businesses create memorable visual identities. I specialize in logo design and brand guidelines.",
    profilePicture: "https://i.pravatar.cc/300?img=32",
    location: getRandomCity(),
    expertise: ["Graphic Design", "Logo Design", "Brand Identity", "Typography", "Design Systems"],
    languages: ["French", "English"],
    pricePerSession: randomPrice(),
    experience: "7 years",
    education: "BA Graphic Design",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },
  {
    name: "Ibrahim Sesay",
    email: "ibrahim.sesay@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Motion graphics designer creating eye-catching animations for brands and social media. Let's bring your designs to life!",
    profilePicture: "https://i.pravatar.cc/300?img=61",
    location: getRandomCity(),
    expertise: ["Graphic Design", "Motion Graphics", "After Effects", "Animation", "Social Media Design"],
    languages: ["English"],
    pricePerSession: randomPrice(),
    experience: "5 years",
    education: "Motion Design Certificate",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },

  // ILLUSTRATION (2 mentors)
  {
    name: "Fatou Sow",
    email: "fatou.sow@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Children's book illustrator bringing stories to vibrant life. I teach illustration fundamentals and character development.",
    profilePicture: "https://i.pravatar.cc/300?img=28",
    location: getRandomCity(),
    expertise: ["Illustration", "Children's Books", "Character Design", "Watercolor", "Storytelling"],
    languages: ["French", "Wolof"],
    pricePerSession: randomPrice(),
    experience: "9 years",
    education: "Illustration Degree",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },
  {
    name: "Michael Omondi",
    email: "michael.omondi@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Editorial and fashion illustrator working with international magazines. I teach ink drawing, fashion sketching, and building your illustration career.",
    profilePicture: "https://i.pravatar.cc/300?img=17",
    location: getRandomCity(),
    expertise: ["Illustration", "Fashion Illustration", "Ink Drawing", "Figure Drawing", "Portfolio Building"],
    languages: ["English", "Swahili"],
    pricePerSession: randomPrice(),
    experience: "11 years",
    education: "Fashion Illustration Diploma",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },

  // MUSIC PRODUCTION (3 mentors)
  {
    name: "Zara Diop",
    email: "zara.diop@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Music producer and sound engineer specializing in Afrobeats, Hip-Hop, and electronic music.",
    profilePicture: "https://i.pravatar.cc/300?img=47",
    location: "Dakar, Senegal",
    expertise: ["Music Production", "Sound Engineering", "Beat Making", "Mixing & Mastering", "Ableton Live", "Logic Pro"],
    languages: ["French", "Wolof", "English"],
    pricePerSession: 55,
    experience: "10 years",
    education: "Diploma in Audio Engineering, SAE Institute",
    rating: 4.7,
    totalRatings: 19,
    completedSessions: 64,
    availability: ["Monday", "Tuesday", "Wednesday", "Thursday"]
  },
  {
    name: "DJ Thabo",
    email: "dj.thabo@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Electronic music producer and DJ. I teach beat production, sound design in FL Studio, and how to release your music.",
    profilePicture: "https://i.pravatar.cc/300?img=54",
    location: getRandomCity(),
    expertise: ["Music Production", "Electronic Music", "FL Studio", "Sound Design", "DJing"],
    languages: ["English", "Setswana"],
    pricePerSession: randomPrice(),
    experience: "8 years",
    education: "Music Production Certificate",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },
  {
    name: "Sarah Mutua",
    email: "sarah.mutua@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Gospel and R&B producer helping artists record professional-quality music from home studios. Specializing in vocal production.",
    profilePicture: "https://i.pravatar.cc/300?img=26",
    location: getRandomCity(),
    expertise: ["Music Production", "Vocal Production", "Recording", "Pro Tools", "R&B", "Gospel Music"],
    languages: ["English", "Kikuyu"],
    pricePerSession: randomPrice(),
    experience: "12 years",
    education: "Audio Production Degree",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },

  // SINGING (3 mentors)
  {
    name: "Grace Afolabi",
    email: "grace.afolabi@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Professional vocalist and voice coach with 15 years of performance experience. I teach vocal technique, breathing, and performance confidence across all genres.",
    profilePicture: "https://i.pravatar.cc/300?img=27",
    location: getRandomCity(),
    expertise: ["Singing", "Vocal Technique", "Performance", "Breath Control", "Music Theory"],
    languages: ["English", "Yoruba"],
    pricePerSession: randomPrice(),
    experience: "15 years",
    education: "BMus Vocal Performance",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },
  {
    name: "Kwesi Boateng",
    email: "kwesi.boateng@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Opera singer and classical voice teacher. I help singers develop proper technique, expand their range, and prepare for auditions.",
    profilePicture: "https://i.pravatar.cc/300?img=62",
    location: getRandomCity(),
    expertise: ["Singing", "Classical Voice", "Opera", "Vocal Health", "Audition Prep"],
    languages: ["English", "Twi", "Italian"],
    pricePerSession: randomPrice(),
    experience: "18 years",
    education: "Master of Music, Vocal Performance",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },
  {
    name: "Amani Mwangi",
    email: "amani.mwangi@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Contemporary and Afrobeat vocalist. I teach modern singing styles, harmonization, and how to record professional vocals.",
    profilePicture: "https://i.pravatar.cc/300?img=35",
    location: getRandomCity(),
    expertise: ["Singing", "Contemporary Voice", "Afrobeats", "Harmonization", "Studio Recording"],
    languages: ["English", "Swahili"],
    pricePerSession: randomPrice(),
    experience: "9 years",
    education: "Contemporary Music Diploma",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },

  // CREATIVE WRITING (3 mentors)
  {
    name: "Fatima Hassan",
    email: "fatima.hassan@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Published author and creative writing coach. I specialize in storytelling, narrative structure, and helping writers find their authentic voice.",
    profilePicture: "https://i.pravatar.cc/300?img=44",
    location: "Cairo, Egypt",
    expertise: ["Creative Writing", "Storytelling", "Novel Writing", "Poetry", "Publishing", "Literary Criticism"],
    languages: ["Arabic", "English", "French"],
    pricePerSession: 42,
    experience: "9 years",
    education: "MA in Creative Writing, American University in Cairo",
    rating: 4.8,
    totalRatings: 27,
    completedSessions: 93,
    availability: ["Tuesday", "Thursday", "Saturday", "Sunday"]
  },
  {
    name: "Ola Adebayo",
    email: "ola.adebayo@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Short story writer and literary magazine editor. I help writers craft compelling narratives and get published.",
    profilePicture: "https://i.pravatar.cc/300?img=19",
    location: getRandomCity(),
    expertise: ["Creative Writing", "Short Stories", "Literary Fiction", "Editing", "Publishing"],
    languages: ["English"],
    pricePerSession: randomPrice(),
    experience: "11 years",
    education: "MFA Creative Writing",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },
  {
    name: "Thandie Moloi",
    email: "thandie.moloi@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Memoir writer and writing workshop facilitator. I guide writers in finding and developing their personal stories with authenticity.",
    profilePicture: "https://i.pravatar.cc/300?img=36",
    location: getRandomCity(),
    expertise: ["Creative Writing", "Memoir", "Personal Essay", "Writing Workshops", "Voice Development"],
    languages: ["English", "Sesotho"],
    pricePerSession: randomPrice(),
    experience: "8 years",
    education: "BA English Literature",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },

  // WEB DEVELOPMENT (3 mentors)
  {
    name: "Kofi Asante",
    email: "kofi.asante@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Full-stack software engineer and tech educator. I've built applications used by millions.",
    profilePicture: "https://i.pravatar.cc/300?img=52",
    location: "Kumasi, Ghana",
    expertise: ["Web Development", "JavaScript", "React", "Node.js", "Mobile App Development", "Python"],
    languages: ["English", "Twi"],
    pricePerSession: 60,
    experience: "11 years",
    education: "BSc Computer Science, KNUST",
    rating: 4.9,
    totalRatings: 38,
    completedSessions: 124,
    availability: ["Monday", "Wednesday", "Thursday", "Saturday"]
  },
  {
    name: "Emmanuel Osei",
    email: "emmanuel.osei@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Frontend developer specializing in modern JavaScript frameworks. I teach React, Vue, and building responsive web applications.",
    profilePicture: "https://i.pravatar.cc/300?img=58",
    location: getRandomCity(),
    expertise: ["Web Development", "Frontend Development", "React", "Vue.js", "CSS", "JavaScript"],
    languages: ["English"],
    pricePerSession: randomPrice(),
    experience: "7 years",
    education: "Web Dev Bootcamp Graduate",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },
  {
    name: "Linda Kamau",
    email: "linda.kamau@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Backend engineer and API architect. I'll teach you Node.js, databases, and how to build scalable server-side applications.",
    profilePicture: "https://i.pravatar.cc/300?img=29",
    location: getRandomCity(),
    expertise: ["Web Development", "Backend Development", "Node.js", "APIs", "MongoDB", "PostgreSQL"],
    languages: ["English", "Swahili"],
    pricePerSession: randomPrice(),
    experience: "9 years",
    education: "BSc Software Engineering",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },

  // DATA SCIENCE (3 mentors)
  {
    name: "Dr. Adeyemi Ogunleye",
    email: "adeyemi.ogunleye@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Data scientist with expertise in machine learning and AI. I teach Python for data science, statistical analysis, and predictive modeling.",
    profilePicture: "https://i.pravatar.cc/300?img=65",
    location: getRandomCity(),
    expertise: ["Data Science", "Machine Learning", "Python", "Statistics", "Data Visualization", "AI"],
    languages: ["English", "Yoruba"],
    pricePerSession: randomPrice(),
    experience: "10 years",
    education: "PhD Computer Science",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },
  {
    name: "Nadia Benzema",
    email: "nadia.benzema@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Business intelligence analyst helping companies make data-driven decisions. I teach SQL, Power BI, and data storytelling.",
    profilePicture: "https://i.pravatar.cc/300?img=31",
    location: getRandomCity(),
    expertise: ["Data Science", "Business Intelligence", "SQL", "Power BI", "Data Analysis", "Excel"],
    languages: ["French", "Arabic", "English"],
    pricePerSession: randomPrice(),
    experience: "8 years",
    education: "MSc Data Analytics",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },
  {
    name: "Samuel Ochieng",
    email: "samuel.ochieng@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Data engineer building data pipelines and analytics platforms. I teach big data technologies, cloud computing, and data engineering.",
    profilePicture: "https://i.pravatar.cc/300?img=63",
    location: getRandomCity(),
    expertise: ["Data Science", "Data Engineering", "Big Data", "Apache Spark", "AWS", "Python"],
    languages: ["English", "Luo"],
    pricePerSession: randomPrice(),
    experience: "12 years",
    education: "MSc Information Systems",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },

  // FILM DIRECTION (2 mentors)
  {
    name: "Tendai Moyo",
    email: "tendai.moyo@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Award-winning filmmaker and cinematographer. I've directed documentaries and commercial projects across Africa.",
    profilePicture: "https://i.pravatar.cc/300?img=57",
    location: "Harare, Zimbabwe",
    expertise: ["Filmmaking", "Film Direction", "Cinematography", "Video Editing", "Documentary", "Premiere Pro", "DaVinci Resolve"],
    languages: ["English", "Shona"],
    pricePerSession: 48,
    experience: "13 years",
    education: "BA Film & Television, University of Zimbabwe",
    rating: 4.8,
    totalRatings: 25,
    completedSessions: 89,
    availability: ["Monday", "Tuesday", "Friday", "Saturday"]
  },
  {
    name: "Amina Kone",
    email: "amina.kone@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Narrative film director specializing in drama and social impact films. I teach directing actors, shot composition, and visual storytelling.",
    profilePicture: "https://i.pravatar.cc/300?img=39",
    location: getRandomCity(),
    expertise: ["Film Direction", "Narrative Film", "Directing Actors", "Shot Composition", "Film Production"],
    languages: ["French", "Bambara"],
    pricePerSession: randomPrice(),
    experience: "14 years",
    education: "MFA Film Direction",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },

  // CINEMATOGRAPHY (2 mentors)
  {
    name: "Joseph Agyeman",
    email: "joseph.agyeman@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Director of photography with cinematic expertise in lighting and camera work. I'll teach you how to create stunning visuals.",
    profilePicture: "https://i.pravatar.cc/300?img=64",
    location: getRandomCity(),
    expertise: ["Cinematography", "Lighting", "Camera Operation", "Color Grading", "Visual Storytelling"],
    languages: ["English"],
    pricePerSession: randomPrice(),
    experience: "15 years",
    education: "Cinematography Certificate",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },
  {
    name: "Yasmine El-Sayed",
    email: "yasmine.elsayed@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Cinematographer specializing in music videos and commercials. I teach camera techniques, lighting setups, and working with small crews.",
    profilePicture: "https://i.pravatar.cc/300?img=34",
    location: getRandomCity(),
    expertise: ["Cinematography", "Music Videos", "Commercial Production", "Lighting Design", "Camera Techniques"],
    languages: ["Arabic", "English"],
    pricePerSession: randomPrice(),
    experience: "10 years",
    education: "BA Film Production",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },

  // BUSINESS STRATEGY (2 mentors)
  {
    name: "David Kimani",
    email: "david.kimani@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Serial entrepreneur and business coach. I've founded 3 successful startups.",
    profilePicture: "https://i.pravatar.cc/300?img=56",
    location: "Nairobi, Kenya",
    expertise: ["Entrepreneurship", "Business Strategy", "Fundraising", "Startup Growth", "Financial Planning"],
    languages: ["English", "Swahili", "Kikuyu"],
    pricePerSession: 65,
    experience: "14 years",
    education: "MBA, Strathmore Business School",
    rating: 4.8,
    totalRatings: 29,
    completedSessions: 98,
    availability: ["Tuesday", "Thursday", "Saturday"]
  },
  {
    name: "Folake Adewale",
    email: "folake.adewale@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Business strategist and consultant helping SMEs scale. I teach market analysis, competitive strategy, and business model development.",
    profilePicture: "https://i.pravatar.cc/300?img=25",
    location: getRandomCity(),
    expertise: ["Business Strategy", "Market Analysis", "Strategic Planning", "Business Models", "Growth Strategy"],
    languages: ["English", "Yoruba"],
    pricePerSession: randomPrice(),
    experience: "16 years",
    education: "MBA Strategy",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },

  // FASHION DESIGN (3 mentors)
  {
    name: "Thandiwe Nkosi",
    email: "thandiwe.nkosi@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Fashion designer celebrating African heritage through contemporary designs.",
    profilePicture: "https://i.pravatar.cc/300?img=49",
    location: "Cape Town, South Africa",
    expertise: ["Fashion Design", "Pattern Making", "Fashion Illustration", "Textile Design", "Brand Development"],
    languages: ["English", "Xhosa", "Afrikaans"],
    pricePerSession: 43,
    experience: "9 years",
    education: "Fashion Design Diploma, Cape Town Fashion Council",
    rating: 4.7,
    totalRatings: 21,
    completedSessions: 76,
    availability: ["Monday", "Wednesday", "Thursday", "Friday"]
  },
  {
    name: "Adama Traore",
    email: "adama.traore@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Sustainable fashion designer creating eco-friendly African fashion. I teach ethical fashion design, upcycling, and building a fashion brand.",
    profilePicture: "https://i.pravatar.cc/300?img=24",
    location: getRandomCity(),
    expertise: ["Fashion Design", "Sustainable Fashion", "Upcycling", "Fashion Business", "Pattern Making"],
    languages: ["French", "Bambara"],
    pricePerSession: randomPrice(),
    experience: "7 years",
    education: "Fashion Design Degree",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },
  {
    name: "Ivy Mwangi",
    email: "ivy.mwangi@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Couture designer specializing in bespoke garments and bridal wear. I teach draping, tailoring, and advanced sewing techniques.",
    profilePicture: "https://i.pravatar.cc/300?img=30",
    location: getRandomCity(),
    expertise: ["Fashion Design", "Couture", "Draping", "Tailoring", "Bridal Wear"],
    languages: ["English", "Swahili"],
    pricePerSession: randomPrice(),
    experience: "12 years",
    education: "Haute Couture Certificate",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },

  // PHOTOGRAPHY (3 mentors)
  {
    name: "Seydou Traore",
    email: "seydou.traore@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Professional photographer specializing in portrait and documentary photography.",
    profilePicture: "https://i.pravatar.cc/300?img=51",
    location: "Bamako, Mali",
    expertise: ["Photography", "Portrait Photography", "Photo Editing", "Lightroom", "Photoshop", "Composition"],
    languages: ["French", "Bambara", "English"],
    pricePerSession: 40,
    experience: "11 years",
    education: "Professional Photography Certificate, Spéos Paris",
    rating: 4.9,
    totalRatings: 36,
    completedSessions: 128,
    availability: ["Tuesday", "Wednesday", "Friday", "Saturday"]
  },
  {
    name: "Chioma Nwosu",
    email: "chioma.nwosu@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Wedding and event photographer capturing life's precious moments. I teach event photography, posing, and building a photography business.",
    profilePicture: "https://i.pravatar.cc/300?img=37",
    location: getRandomCity(),
    expertise: ["Photography", "Wedding Photography", "Event Photography", "Posing", "Business"],
    languages: ["English", "Igbo"],
    pricePerSession: randomPrice(),
    experience: "8 years",
    education: "Photography Diploma",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },
  {
    name: "Hassan Mahmoud",
    email: "hassan.mahmoud@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Commercial and product photographer working with major brands. I teach studio lighting, product photography, and post-production.",
    profilePicture: "https://i.pravatar.cc/300?img=66",
    location: getRandomCity(),
    expertise: ["Photography", "Product Photography", "Commercial Photography", "Studio Lighting", "Retouching"],
    languages: ["Arabic", "English"],
    pricePerSession: randomPrice(),
    experience: "13 years",
    education: "Commercial Photography Certificate",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },

  // DANCE CHOREOGRAPHY (3 mentors)
  {
    name: "Amina Yusuf",
    email: "amina.yusuf@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Professional dancer and choreographer specializing in contemporary African dance.",
    profilePicture: "https://i.pravatar.cc/300?img=43",
    location: "Addis Ababa, Ethiopia",
    expertise: ["Contemporary Dance", "African Dance", "Dance Choreography", "Performance Art", "Dance Teaching"],
    languages: ["Amharic", "English"],
    pricePerSession: 38,
    experience: "10 years",
    education: "BA Performing Arts, Addis Ababa University",
    rating: 4.8,
    totalRatings: 20,
    completedSessions: 72,
    availability: ["Monday", "Tuesday", "Thursday", "Sunday"]
  },
  {
    name: "Pierre Nzabakira",
    email: "pierre.nzabakira@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Hip-hop choreographer and dance crew director. I teach urban dance styles, battle strategies, and creating performance routines.",
    profilePicture: "https://i.pravatar.cc/300?img=69",
    location: getRandomCity(),
    expertise: ["Dance Choreography", "Hip-Hop Dance", "Breaking", "Urban Dance", "Performance"],
    languages: ["French", "Kinyarwanda", "English"],
    pricePerSession: randomPrice(),
    experience: "9 years",
    education: "Street Dance Certificate",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },
  {
    name: "Lebo Molefe",
    email: "lebo.molefe@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Traditional and fusion dance choreographer blending African dance with modern styles. I teach cultural dance and choreography for performances.",
    profilePicture: "https://i.pravatar.cc/300?img=22",
    location: getRandomCity(),
    expertise: ["Dance Choreography", "Traditional Dance", "Fusion Dance", "Cultural Dance", "Stage Performance"],
    languages: ["English", "Setswana", "Zulu"],
    pricePerSession: randomPrice(),
    experience: "14 years",
    education: "Performing Arts Degree",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },

  // ANIMATION (3 mentors)
  {
    name: "Malik Diallo",
    email: "malik.diallo@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "3D artist and animator working in games and film.",
    profilePicture: "https://i.pravatar.cc/300?img=13",
    location: "Abidjan, Côte d'Ivoire",
    expertise: ["3D Modeling", "Animation", "Blender", "Maya", "Game Design", "Character Design"],
    languages: ["French", "English"],
    pricePerSession: 47,
    experience: "8 years",
    education: "BA Animation, ESMA Montpellier",
    rating: 4.7,
    totalRatings: 16,
    completedSessions: 54,
    availability: ["Tuesday", "Thursday", "Friday", "Sunday"]
  },
  {
    name: "Sophie Banda",
    email: "sophie.banda@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "2D animator creating explainer videos and animated shorts. I teach After Effects, character animation, and storyboarding.",
    profilePicture: "https://i.pravatar.cc/300?img=23",
    location: getRandomCity(),
    expertise: ["Animation", "2D Animation", "After Effects", "Character Animation", "Storyboarding"],
    languages: ["English"],
    pricePerSession: randomPrice(),
    experience: "7 years",
    education: "Animation Degree",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },
  {
    name: "Omar Farah",
    email: "omar.farah@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Motion designer and animator for advertising. I create dynamic animations for brands and teach motion design principles.",
    profilePicture: "https://i.pravatar.cc/300?img=67",
    location: getRandomCity(),
    expertise: ["Animation", "Motion Design", "Cinema 4D", "After Effects", "Visual Effects"],
    languages: ["Arabic", "English", "Somali"],
    pricePerSession: randomPrice(),
    experience: "10 years",
    education: "Motion Graphics Certificate",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },

  // UI/UX DESIGN (3 mentors)
  {
    name: "Aisha Mohammed",
    email: "aisha.mohammed@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "UX/UI designer passionate about creating intuitive digital experiences.",
    profilePicture: "https://i.pravatar.cc/300?img=48",
    location: "Kigali, Rwanda",
    expertise: ["UX Design", "UI Design", "Figma", "User Research", "Design Thinking", "Prototyping"],
    languages: ["English", "Kinyarwanda", "French"],
    pricePerSession: 52,
    experience: "6 years",
    education: "BSc Information Technology, University of Rwanda",
    rating: 4.7,
    totalRatings: 18,
    completedSessions: 56,
    availability: ["Tuesday", "Wednesday", "Thursday", "Sunday"]
  },
  {
    name: "Tunde Bakare",
    email: "tunde.bakare@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Product designer working with startups and tech companies. I teach UI design, design systems, and crafting delightful user experiences.",
    profilePicture: "https://i.pravatar.cc/300?img=68",
    location: getRandomCity(),
    expertise: ["UI/UX Design", "Product Design", "Design Systems", "Figma", "Adobe XD"],
    languages: ["English", "Yoruba"],
    pricePerSession: randomPrice(),
    experience: "8 years",
    education: "BSc Computer Science",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },
  {
    name: "Leila Nabwire",
    email: "leila.nabwire@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "UX researcher helping companies understand their users. I teach user research methods, usability testing, and data-driven design.",
    profilePicture: "https://i.pravatar.cc/300?img=21",
    location: getRandomCity(),
    expertise: ["UI/UX Design", "User Research", "Usability Testing", "UX Strategy", "Research Methods"],
    languages: ["English", "Luganda"],
    pricePerSession: randomPrice(),
    experience: "9 years",
    education: "MSc Human-Computer Interaction",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },

  // VIDEO EDITING (3 mentors)
  {
    name: "Nkechi Adeyemi",
    email: "nkechi.adeyemi@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Video content creator and YouTube strategist.",
    profilePicture: "https://i.pravatar.cc/300?img=46",
    location: "Lagos, Nigeria",
    expertise: ["Content Creation", "YouTube Strategy", "Video Editing", "Video Marketing", "Social Media", "Final Cut Pro"],
    languages: ["English", "Yoruba"],
    pricePerSession: 35,
    experience: "5 years",
    education: "BA Mass Communication, University of Lagos",
    rating: 4.9,
    totalRatings: 44,
    completedSessions: 167,
    availability: ["Monday", "Wednesday", "Friday", "Sunday"]
  },
  {
    name: "Jean-Paul Mutombo",
    email: "jeanpaul.mutombo@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Professional video editor for film and television. I teach advanced editing techniques, color correction, and storytelling through editing.",
    profilePicture: "https://i.pravatar.cc/300?img=70",
    location: getRandomCity(),
    expertise: ["Video Editing", "Premiere Pro", "DaVinci Resolve", "Color Grading", "Post-Production"],
    languages: ["French", "Lingala", "English"],
    pricePerSession: randomPrice(),
    experience: "12 years",
    education: "Film Editing Certificate",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },
  {
    name: "Abena Owusu",
    email: "abena.owusu@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Social media video editor creating viral content. I teach fast-paced editing, transitions, and creating engaging short-form videos.",
    profilePicture: "https://i.pravatar.cc/300?img=20",
    location: getRandomCity(),
    expertise: ["Video Editing", "Social Media Video", "CapCut", "Mobile Editing", "Short-Form Content"],
    languages: ["English", "Twi"],
    pricePerSession: randomPrice(),
    experience: "4 years",
    education: "Content Creation Bootcamp",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },

  // SCREENWRITING (3 mentors)
  {
    name: "Chidi Okoro",
    email: "chidi.okoro@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Content strategist and copywriter helping brands tell compelling stories.",
    profilePicture: "https://i.pravatar.cc/300?img=15",
    location: "Nairobi, Kenya",
    expertise: ["Copywriting", "Content Strategy", "Screenwriting", "SEO Writing", "Digital Marketing", "Brand Storytelling"],
    languages: ["English", "Swahili"],
    pricePerSession: 38,
    experience: "7 years",
    education: "BA in Journalism, University of Nairobi",
    rating: 4.6,
    totalRatings: 22,
    completedSessions: 71,
    availability: ["Monday", "Tuesday", "Wednesday", "Friday"]
  },
  {
    name: "Zanele Dlamini",
    email: "zanele.dlamini@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Film and TV screenwriter with produced works on major African networks. I teach screenplay structure, dialogue, and pitching scripts.",
    profilePicture: "https://i.pravatar.cc/300?img=33",
    location: getRandomCity(),
    expertise: ["Screenwriting", "TV Writing", "Screenplay Structure", "Dialogue", "Pitching"],
    languages: ["English", "Zulu", "Swazi"],
    pricePerSession: randomPrice(),
    experience: "11 years",
    education: "MFA Screenwriting",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },
  {
    name: "Dele Ojo",
    email: "dele.ojo@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Nollywood screenwriter and script doctor. I help writers craft compelling African stories and develop their screenwriting careers.",
    profilePicture: "https://i.pravatar.cc/300?img=72",
    location: getRandomCity(),
    expertise: ["Screenwriting", "Film Writing", "Script Development", "Story Structure", "Character Development"],
    languages: ["English", "Yoruba"],
    pricePerSession: randomPrice(),
    experience: "15 years",
    education: "BA Creative Writing",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },

  // GAME DEVELOPMENT (3 mentors)
  {
    name: "Tendeka Moyo",
    email: "tendeka.moyo@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Indie game developer creating mobile and PC games. I teach Unity, C#, and the complete game development pipeline from concept to launch.",
    profilePicture: "https://i.pravatar.cc/300?img=71",
    location: getRandomCity(),
    expertise: ["Game Development", "Unity", "C#", "Mobile Games", "Game Design"],
    languages: ["English", "Shona"],
    pricePerSession: randomPrice(),
    experience: "9 years",
    education: "BSc Game Development",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },
  {
    name: "Amara Chukwu",
    email: "amara.chukwu@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Game designer and level designer working on AAA titles. I teach game mechanics, level design, and player experience.",
    profilePicture: "https://i.pravatar.cc/300?img=42",
    location: getRandomCity(),
    expertise: ["Game Development", "Game Design", "Level Design", "Unreal Engine", "Game Mechanics"],
    languages: ["English", "Igbo"],
    pricePerSession: randomPrice(),
    experience: "10 years",
    education: "Game Design Degree",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },
  {
    name: "Sipho Ndlovu",
    email: "sipho.ndlovu@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "VR/AR developer creating immersive experiences. I teach game programming, virtual reality development, and 3D for games.",
    profilePicture: "https://i.pravatar.cc/300?img=73",
    location: getRandomCity(),
    expertise: ["Game Development", "VR Development", "AR Development", "Unity", "Unreal Engine"],
    languages: ["English", "Zulu", "Xhosa"],
    pricePerSession: randomPrice(),
    experience: "7 years",
    education: "Interactive Media Degree",
    rating: parseFloat(randomRating()),
    totalRatings: randomRatingsCount(),
    completedSessions: randomSessions(),
    availability: getRandomAvailability()
  },

  // Additional mentors for other existing skills
  // PHYSICS
  {
    name: "Dr. Chinonso Okafor",
    email: "chinonso.okafor@cre8.com",
    password: "password123",
    role: "mentor",
    bio: "Physics professor and STEM education advocate.",
    profilePicture: "https://i.pravatar.cc/300?img=59",
    location: "Abuja, Nigeria",
    expertise: ["Physics", "Mathematics", "STEM Education", "Research Methods", "Academic Writing"],
    languages: ["English", "Igbo"],
    pricePerSession: 50,
    experience: "16 years",
    education: "PhD in Physics, University of Ibadan",
    rating: 4.9,
    totalRatings: 33,
    completedSessions: 142,
    availability: ["Monday", "Wednesday", "Friday", "Saturday"]
  }
];

const seedMentors = async () => {
  try {
    await connectDB();
    
    console.log('🗑️  Clearing existing mentors...');
    await Mentor.deleteMany({});
    
    console.log('👥 Creating mentor accounts...');
    
    for (const mentorData of mentorsData) {
      const salt = await bcrypt.genSalt(10);
      const hashedPassword = await bcrypt.hash(mentorData.password, salt);
      
      const mentor = await Mentor.create({
        ...mentorData,
        password: hashedPassword
      });
      
      const expertiseStr = mentorData.expertise ? mentorData.expertise.join(', ') : 'N/A';
      console.log(`✅ Created mentor: ${mentor.name} - ${expertiseStr}`);
    }
    
    console.log('\n🎉 Successfully seeded', mentorsData.length, 'mentors!');
    console.log('\n📧 Login credentials for all mentors:');
    console.log('Password: password123\n');
    
    process.exit(0);
  } catch (error) {
    console.error('Error seeding mentors:', error);
    process.exit(1);
  }
};

seedMentors();
